/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package market_system.backtest.view;

import market_system.backtest.BackTest;

/**
 *
 * @author Fabrizio Ortega
 */
public class BackTestResultPanel extends javax.swing.JPanel {
    BackTest backtest;
    /**
     * Creates new form BackTestResultPanel
     */
    public BackTestResultPanel() {
        initComponents();
    }
    public BackTestResultPanel(BackTest backtest) {
        this.backtest = backtest;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        balancePanel1 = new market_system.backtest.view.results.BalancePanel(backtest);
        market_system.backtest.view.results.TradesPanel tradesPanel1 = new market_system.backtest.view.results.TradesPanel(backtest);

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        setMaximumSize(new java.awt.Dimension(2180, 300));
        setMinimumSize(new java.awt.Dimension(2180, 300));

        jTabbedPane1.setMaximumSize(new java.awt.Dimension(2180, 300));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(2180, 300));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(2180, 300));
        jTabbedPane1.addTab("Balance", balancePanel1);
        jTabbedPane1.addTab("Trades", tradesPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private market_system.backtest.view.results.BalancePanel balancePanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
