<S> -> <S><IF>|<IF>.
<IF> -> if(<COND>'){'<RES>';}'|if(<COND>'){'<RES>';}else{'<RES>';}'.
<COND> -> <OBS> <OP> <VALUE> | <OBS> <OP> <OBS> |'(' <COND> <OP_RELA> <COND>')'.
<OP> -> '<'|'>'|'<='|'>='.
<OP_RELA> -> '&&'|'||'.
<VALUE> -> '-'<V>'.'<N>|<V>'.'<N>.
<V> -> 0|1|2|3.
<RES> -> <RES_BULL>|<RES_BEAR>|'res.bull=0'|'res.bear=0'.
<RES_BULL> -> 'res.bull=res.bull+'<N>.
<RES_BEAR> -> 'res.bear=res.bear+'<N>.
<N> -> 0|1|2|3|4|5|6|7|8|9.
<OBS> -> 'Momentum10'|'Momentum50'|'Momentum200'|'Macd10_30'|'Macd50_100'|'Macd100_200'.